### ISSUE TITLE
[Doubles/Triples] Pressure's interaction with multi-target moves is incorrect

### ISSUE THREAD

**Issue by ascriptmaster** [Zarel/Pokemon-Showdown#1443]
(making the note for myself)

- Using a multi-target move on multiple mons with Pressure only deducts 2 PP, not 1 + (1 per Pressure mon)
- ~~Using field-targetting moves like Stealth Rock or Rain Dance deduct 2 PP instead of 1.~~

**Comment by Zarel** [comment]
I thought I fixed this ages ago. Did someone change Pressure again? :|

**Comment by ascriptmaster** [comment]
Pressure has a strange interaction with the event system, where if multiple Pokemon on one side have Pressure during a multi-target attack, Pressure's `onDeductPP` handler only activates once, instead of going off for each Pressure Pokemon targeted.

**Comment by Zarel** [comment]
Can you figure out why and fix it?

**Comment by ascriptmaster** [comment]
I'm still looking at it.

**Comment by ascriptmaster** [comment]
Bumping this with the new information about how non-Ghost Curse causes 2 PP to deduct.

@Marty-D can you verify the amount of PP that should be lost with side-targetting moves (Stealth Rock) and field-targetting moves (Rain Dance) with multiple Pressure mons on the field?

I'll work on this... next. Maybe.

**Comment by Marty-D** [comment]
It depends on the generation. In Gen 3 and 4, Pressure works on allies but since Gen 5 it doesn't. So in Gen 4 Doubles for example, if every Pokemon has Pressure and one uses Explosion, it loses 4 PP, but in Gen 5 it loses 3 PP.

For specific answers: Stealth Rock targets all opposing Pokemon and Rain Dance targets all Pokemon, so you'd lose 3 PP for Stealth Rock and Rain Dance is the same as the above Explosion example. In Gen 3 though, Rain Dance only targets the user so it's not affected by Pressure at all (but that's a different issue; Gen 1-3 move targets are fairly different and I'll address that eventually™).

Related: Imprison and Snatch are considered to target all opposing Pokemon for the purposes of Pressure, even if they don't seal or steal any moves.

**Comment by ascriptmaster** [comment]
Oh, I forgot about Snatch and Imprison! Are there any other moves like that?

Most of the rest was fixed in #2006

**Comment by ascriptmaster** [comment]
I think we're done with this now that Snatch and Imprison are coded properly
