### ISSUE TITLE
Implement Nickname Clause fully

### ISSUE THREAD

**Issue by Slayer95** [Zarel/Pokemon-Showdown#1445]
VGC 2015 rules state <code>A player’s team cannot contain two Pokémon with the same nickname</code>. This has apparently been in the ruleset for more than one edition.

Under normal conditions, this rule is play-wise irrelevant, so it initially made sense to implement it globally and not only for VGC 2015. However, for metagames without Species Clause, such as Anything Goes, sharing nicknames can be used as a (imo very valid) deception strategy.

Opening this issue so we get some actual discussion before hell breaks loose.

**Comment by Marty-D** [comment]
While that rule is indeed irrelevant in Singles with Species Clause, in Doubles there are cases where it is relevant (which is probably why the rule exists). For example, if both of your active Pokemon have the same nickname (or are the same Pokemon with no nickname), and your opponent uses a single-target move and misses, you won't know which of your Pokemon was targeted since the animation doesn't happen. This only became relevant after Gen 4 because the single-target 'move missed' message changed from 'user missed' to 'target avoided', like spread moves.
