### ISSUE TITLE
Air Lock and Cloud Nine difficulties

### ISSUE THREAD

**Issue by WreckDra** [Zarel/Pokemon-Showdown#1789]
|switch|p1a: Deoxys|Deoxys|100/100

|-ability|p1a: Deoxys|Pressure
|switch|p2a: Rayquaza|Rayquaza|372/372

|-ability|p2a: Rayquaza|Air Lock
|
|-weather|Sandstorm|[upkeep]
|-damage|p1a: Deoxys|94/100|[from] sandstorm

|turn|2

To be quite frank, the way the abilities are set up this shouldn't happen. I have been scratching my head on this for awhile, as has Marty D, but we have been unable to figure out why this happens at all. This also applies to Solar Power, Rain Dish / Dry Skin, hail etc.

**Comment by gamut-was-taken** [comment]
This is a guess but what if [Air Lock][1] and [Cloud Nine][2] were modified to trigger `onAnyUpdate` instead of `onAnyModifyPokemon`?

  [1]: https://github.com/Zarel/Pokemon-Showdown/blob/master/data/abilities.js#L92
  [2]: https://github.com/Zarel/Pokemon-Showdown/blob/master/data/abilities.js#L329

In the case of Deoxys vs Rayquaza above: after Rayquaza is switched in Deoxys does not undergo the `ModifyPokemon` event until after the `TryWeather` event, and by then Deoxys has already taken damage from the sand. I think the trigger should be `onAnyUpdate` because Deoxys undergoes the `Update` event twice between the period Rayquaza is switched in and before the `TryWeather` event.

**Comment by WreckDra** [comment]
Oh wow, that actually sounds perfect. I didnt realize ModifyPokemon took place after TryWeather. I need to study Battle scripts a bit more I guess.

**Comment by ascriptmaster** [comment]
Fixed by #1855
