### ISSUE TITLE
[Feature Suggestion] API to get currently online Users in a Room

### ISSUE THREAD

**Issue by masterofjellyfish** [Zarel/Pokemon-Showdown#1946]
Hi,

I'd like to request an API to programmatically get the users online in a room, without writing a bot that idles in the room for soley this purpose.

General use case is that I want to pull this information like every 5 minutes or so and display it beneath the "who is online" list in our forums.

I'd have implemented it myself and sent you a PR, however I don't know neither javascript nor node.js good enough to produce code I'm not ashamed of.

**Comment by Zarel** [comment]
That sounds like a pretty obscure use-case. I'd recommend either writing a bot or submitting the pull request yourself, or finding someone to do one of those two things for you.

I'm closing because I don't think any of us are interested in implementing this feature for you, and I don't think it's of interest to the general public. Sorry. :(
