### ISSUE TITLE
Bundle a process manager with the server

### ISSUE THREAD

**Issue by kotarou3** [Zarel/Pokemon-Showdown#2244]
http://pm2.keymetrics.io/ looks pretty interesting, has all sorts of features that forever/nohup/screen by themselves don't provide.

Could also be helpful for the recent server crashes since it auto restarts it like forever does.

**Comment by Zarel** [comment]
232 subdependencies.

Would increase PS's production dependency count from 3 to 235, massively slowing down first-launch...

**Comment by Zarel** [comment]
I was thinking of bundling a process manager, but this one is kind of ridiculous.

**Comment by scheibo** [comment]
The seems obsolete?

**Comment by Zarel** [comment]
I really did want to bundle a process manager though... :(

What's our production dependency count these days?

**Comment by scheibo** [comment]
Sorry, was just trying to do some housekeeping. Our total graph is current as follows:

![deps](https://user-images.githubusercontent.com/117249/57317693-8edcd100-70ad-11e9-81fe-f837b72777d9.png)

Primarily due to `probe-image-size` (or rather, primary due to its `request` sub package). Interestingly, it already brings in `fast-deep-equal` and `fast-json-stable-stringify`, which I deliberately avoided using on the `toJSON` PR, guess there was no point.

Do we need `probe-image-size`? Just for `Chat.getImageDimensions` used by some chat plugins? Seems like a waste. *'small size, no heavy dependencies' lol. `request` seems pretty heavy to me?* I wonder if a solution like https://github.com/image-size/image-size#using-a-url (`image-size` has **no** deps) would be useful, if we do in fact need to support the feature?

---

I can't actually speak to the actual question of whether a process manager should be bundled given that I don't run a PS server, but it seems wrong to me, if I owned a server I'd rather make a choice myself about `upstart` / `daemontools` / `supervisord` etc to match what other services I host rather than have an arbitrary one hoisted on me by the project?

**Comment by Zarel** [comment]
Yeah, that's fair.

We don't need `probe-image-size`, it's intended as a solution for something that should be done client-side anyway, but you know how long Preact rewrite's been delayed.

**Comment by Zarel** [comment]
https://twitter.com/lukejacksonn/status/1131506699356037121

![image](https://user-images.githubusercontent.com/551184/58752624-0406b080-8478-11e9-8f0d-8dcce2f403db.png)

**Comment by Zarel** [comment]
I was completely 800% correct to be leery of 232 subdependencies!

**Comment by Zarel** [comment]
https://github.com/Unitech/pm2/issues/4289#issuecomment-495157865
