### ISSUE TITLE
Sylveon and Mamoswine can inherit too many moves from their pre-evolutions

### ISSUE THREAD

**Issue by meew0** [Zarel/Pokemon-Showdown#2249]
Eevee (to Sylveon) and Piloswine both evolve by knowing a certain move (any Fairy-type move and Ancient Power, respectively). This means they should only be able to pass on three other moves. However, this is not implemented in Pokémon Showdown.

Relevant moves for Mamoswine are Tackle, Ice Shard, Flail, Amnesia and Fury Attack. Relevant moves for Sylveon are Refresh, Bite, Growl, Take Down, Double-Edge, Trump Card, Baton Pass. If the three other moveslots are filled, then only one of Covet and Baby-Doll Eyes should be inherited.

Theoretically, this could also apply to Ambipom, Lickilicky, Mr. Mime, Sudowoodo, Tangrowth and Yanmega, however, these Pokémon all have fewer than four moves exclusive to pre-evolutions.

**Comment by Zarel** [comment]
This is competitively relevant? (That's mostly to determine how high-priority this bug is)

**Comment by Marty-D** [comment]
Probably not very in Gen 6, but this does extend to egg moves prior to Gen 6. Since Gen 5 and earlier had no way to relearn egg moves once forgotten, any Pokemon that evolves by knowing a move can't have 4 egg exclusive moves as a moveset.

Even in Gen 6 though, prior to ORAS this was a legitimate problem for Sylveon because a set of Hyper Voice, Heal Bell, Wish, and Baton Pass was impossible to obtain legally. Hyper Voice and Heal Bell were Gen 5 tutor moves for Eevee, Wish is an egg move, and Baton Pass is a level-up move for Eevee only. Once you evolved it in Gen 6, you were forced to lose one of the moves and none of them could be relearned because Wish was bred in Gen 5. IIRC this illegality was hardcoded at the time.

**Comment by jakobw** [comment]
I'd like to tackle this issue. It looks like only Mamoswine in Gen5 and Gen4 is relevant here since Sylveon is only a problem in X&Y which is not a tier.
For Mamoswine the problematic moveset is Tackle, Ice Shard, Amnesia and Fury Attack. Icy wind is only an egg move in Gen5 where it is also a tutor move, so that's not an issue. Flail is only an egg move in Gen6 which we don't need to address.

**Comment by Zarel** [comment]
See #2287
