### ISSUE TITLE
.svg Male/Female signs; Mega symbol

### ISSUE THREAD

**Issue by VineST** [Zarel/Pokemon-Showdown#2430]
Just some small quality of life stuff for high resolution viewing.

**Comment by Zarel** [comment]
I hope SVG support/performance is acceptable in these modern times...

**Comment by Zarel** [comment]
I don't think SVG adds anything.

Our male/female symbols used to be vector, but it turns out the pixelated versions are much clearer.

If someone actively pull requests vector versions, we can discuss whether or not that specific pull request looks better, but I don't consider vector graphics a relevant overall direction for PS to pursue.
