### ISSUE TITLE
Shedinja can learn substitute

### ISSUE THREAD

**Issue by Arburator** [Zarel/Pokemon-Showdown#2459]
How can a 1 HP pokemon use substitute, seriously, Why is it valid?

Check: http://prntscr.com/al0urn

**Comment by FlyingTypesRule** [comment]
This isn't the place for minor bugs like this - not to mention that it's not a bug at all.

Shedinja, through TM90, can learn Protect in-game.  In order to stay true to the game, PS! gives Shedinja the move Substitute because Sheddy can get it.  While it is indeed useless, that's GameFreak's fault, not PS's.  (not to mention that sheddy can still get sub from nincada even if GF prevented it from getting sub)

**Comment by Zarel** [comment]
The reason we don't allow mechanics bugs to be reported is because most of them, like this, aren't even wrong. Users are pretty bad at understanding how game mechanics work. We suggest Bug Reports for this:

http://psim.us/bugreports
