### ISSUE TITLE
Strange bug with swapped hp/movesets

### ISSUE THREAD

**Issue by BanAvoider** [Zarel/Pokemon-Showdown#2597]
http://replay.pokemonshowdown.com/hackmonscup-391173234

sentret somehow gained the moveset and hp of throh

happened in hackmons cup

**Comment by Marty-D** [comment]
Clearly Throh had Illusion. That's also why Fissure didn't affect Clefairy; it wasn't actually level 97 because it wasn't Sentret.

Please post bug reports in the [bug reports thread](http://www.smogon.com/forums/threads/bug-reports-v2-0-read-op-before-posting.3469932/) in the future - chances are they aren't actually bugs and certainly don't belong as issues on GitHub.
