### ISSUE TITLE
Timer sets both players to 40sec upon disconnect

### ISSUE THREAD

**Issue by jake-white** [Zarel/Pokemon-Showdown#2769]
I have had this happen to me several times and it seems like a bug, not a feature.  If you turn on the timer when someone disconnects, and they come back, the person who did not disconnect is also set on a 40-second timer.  This means anyone can DC to force their opponent to <40 seconds instantly. (Not to mention it's hardly fair for someone who never disconnected in the first place to have a reduced timer). 

It happens a lot in my case because I turn on the timer, tab out as I wait for them to reconnect or for the timer to run out, and tab back in ~40 seconds later to see that I've just lost.

![timerissue](https://cloud.githubusercontent.com/assets/6503932/18730536/df3d630c-8024-11e6-85d5-bc5e95abe7cd.PNG)

**Comment by Zarel** [comment]
I completely misinterpreted this issue as reporting that the timer was 40 seconds instead of 60 seconds, which seemed like a hard debugging problem. (The timer is actually 60 seconds, there's 20 seconds between "Battle timer is now ON" and "NAME has 40 seconds left".)

But actually after rereading this, I understand the problem and it's a really easy fix.

**Comment by Zarel** [comment]
Fixed in 9031680e5d
