### ISSUE TITLE
Add a "Suggest Draw" option in battles

### ISSUE THREAD

**Issue by CamiloTD** [Zarel/Pokemon-Showdown#2812]
Sometimes, we dont like to battle a friend in rated battles, or we made a mistake in tournament and we wanted to tie, there should be a "Suggest Draw" option or command, that allow both players agree a tie.

**Comment by Zarel** [comment]
No.

**Comment by Zarel** [comment]
I would suspect most tournament organizers are opposed to drawing instead of actually playing out your battles.

For casual battles, you can verbally agree to a draw and one of you can forfeit, you don't really need the battle log itself to say it's a tie.

For rated battles, I believe consensus is that an "offer draw" feature would not be desirable. You may wish to start a forum thread if you want to build consensus out of that.
