### ISSUE TITLE
Fix remaining Z-Move issues

### ISSUE THREAD

**Issue by Slayer95** [Zarel/Pokemon-Showdown#2949]
Tracking bug for Z-Moves remaining issues.

(Checklist copied from [Mechanics Research thread](http://www.smogon.com/forums/threads/3586701/) 11/26)

- [x] Damaging Z-Moves DO NOT carry over secondary effects/attributes from their base moves (i.e increased priority, status affliction, etc). They are their own unique moves. (Kalalokki)
- [x] Z-Status moves apply their Z-effect before applying the move's own effect (ex: Z-Belly Drum will heal the user by 100% of their HP before removing 50% to boost their stats by +6). Status Z-moves function in the same priority bracket as their base moves. Status Z-moves gain +1 priority from Prankster and other abilities. (squirrelboyVGC) (yetanotherperson)
- [x] You can use 1 Z-Move per battle, it is independent from Mega Evolution.
- [x] Z-Moves benefit from abilities such as Mold Breaker, Scrappy, Hustle and others. (Kalalokki)
- [x] Damaging Z-Moves can deal critical hits. (ih8ih8sn0w)
- [x] Z-status move's Z-Power bonus effects (Z-Power effects applied before the Z-move is used, such as restoring HP or boosting stats) are not affected by Snatch or Magic Bounce, the following Z-move is affected in the same manner its base move is. (UltiMario)
- [x] Z-Moves are affected by abilities that affect damage or redirect such as Storm Drain and LightningRod. (yetanotherperson)
- [x] Draining the PP of the base move prevents the corresponding Z-move from being used. (OmegaDonut)
- [x] Disabling or Imprisoning the base move does not prevent the Z-move from being used. (OmegaDonut)
- [x] Z-Moves used while the user has the ability Protean will change the Pokemon's type to match the Z-move's type. (Kalalokki)
- [x] Z-Nature Power transforms into the respective Z-move based on terrain (i.e Energy Ball -> Bloom Doom, Earth Power -> Tectonic Edge) (OmegaDonut)
- [x] Z-Hidden power always transforms into Breakneck Blitz regardless of type. (OmegaDonut)
- [x] "couldn't fully protect itself" means damaging Z-Moves bypass Protect but deal reduced damage (roughly 25% of original) regardless if its a critical hit or not (OmegaDonut)
- [x] Z-Belly Drum restores all HP before deducting the 50%, so it can be used below 50% health. (OmegaDonut)
- [x] Z-Parting Shot and Z-Memento also restore HP of the incoming Pokemon (need to test the amount). (OmegaDonut)
- [x] Z-Crystals can't be Knocked Off and caused Trick, Switcheroo, and Fling to fail (yetanotherperson) and are not consumed after using a Z-move. (OmegaDonut)
- [x] Z-Moves are not affected by type changing abilities (Refrigerate, Pixilate, etc)
- [x] Z-moves do not bypass Disguise. (OmegaDonut)
- [x] POKEMON returned its decreased stats to normal using its Z-Power!. Stat resetting Z-effects remove lowered stats not boosted stat changes, similar to White Herb.
- [x] Z-Geomancy still requires a charge turn after applying its Z-effect. (ih8ih8sn0w)
- [x] Pokemon can use Z-Status moves while under the effects of Taunt (UltiMario)
- [x] The 25% damage reduction from Protect to Z-Moves also applies to percentage based damaging Z-moves like Guardian of Alola. (OmegaDonut)
- [x] Fire/Water Z-moves will fizz/evaporate in Heavy Rain/Harsh Sunlight (yetanotherperson)
- [x] Z-Trick only has the specific Z-effect happen but the move itself will fail afterwards since Z-Crystals can't be removed by Trick. (Kalalokki)
- [x] Z-Status moves do not have perfect accuracy like damaging Z-moves. (OmegaDonut)
- [x] Purify Z-Move all-stats up effect is applied to the user not the target. Purify does not need to succeed to give those stat boosts, in-game message: ""X increased its stats using its Z-Power! X unleashes its full force Z-Move! X used Purify! But it failed!" (UltiMario)
- [x] Z-Mirror Move will reflect the opposing Pokemon's attack as its Z-Move equivalent (ex: Icy Wind reflected off Z-Mirror Move will become Subzero Slammer) after applying the +2 boost in attack from its Z-Power effect. (Source)
- [x] Z-Me First works similarly to Z-Mirror Move, the Z-Move variant of the target's move will be used regardless of the Pokemon's Z-Crystal with the Z-Power effect of Me First (Boosts Speed by 2 stages) being applied first. Z-Copycat works in a similar fashion, applying its unique Z-Power effect before using the Z-move variant. (yetanotherperson)
- [x] All stat increase status Z-move effects do not increase accuracy and evasion. (UltiMario)
- [x] After applying its Z-effect, Z-Sleep Talk calls upon a random move in the user's move set and uses its corresponding Z-move (ex: Water-type move becomes Hydro Vortex) regardless of their Z-crystal or the move's type. (ih8ih8sn0w) Z-status moves do not gain their Z-Power bonus effect and the move is executed as normal (Blitzamirin)
- [x] While affected by Encore a Pokemon still has the option to use its Z-move even if its base move was the move that was Encored. (OmegaDonut) Encore will fail against a Pokemon that previously used a Z-move (LegoFigure11)
- [x] When hacked into normal move slots, damaging Z-moves (Hydro Vortex, Bloom Doom, etc) becomes 1 BP / -- Accuracy moves of their respective types. Special Z-moves (Catastropika, pulverizing Pancake, etc) function normally with their actual Base Powers and effects. All normal move slot Z-Moves have 1 PP ( PP Ups don't work). You can use as many normal move slot Z-Moves as you want in a battle. You cannot power up a normal slot Z-Move with a Z-Crystal (it won't recognize the move as that typing at all). (UltiMario) Their PP can be restored with a Leppa Berry. (UltiMario)
- [x] Pokemon that have transformed due to Imposter or Transform can use a Z-move using that transformed Pokemon's move set as long as they hold the corresponding Z-Crystal. (ih8ih8sn0w)
- [x] Copycat cannot copy Z-moves. (ih8ih8sn0w)

**Comment by acz13** [comment]
Which of these still have to be fixed? Some of them seem to be OK

**Comment by HoeenCoder** [comment]
Id assume this falls under this issue. http://www.smogon.com/forums/threads/bug-reports-v2-0-read-op-before-posting.3469932/page-333#post-7243197

**Comment by Slayer95** [comment]
Updated the list from @HoeenCoder 's comment and @ascriptmaster 's commit.

**Comment by Zarel** [comment]
Z-Hidden Power already works as described. Can someone go through the remaining unchecked things and tell me which are and aren't done?

**Comment by HoeenCoder** [comment]
- Z-Moves benefit from abilities such as Mold Breaker, Scrappy, Hustle and others. (Kalalokki)
 - Z-status move's Z-Power bonus effects (Z-Power effects applied before the Z-move is used, such as restoring HP or boosting stats) are not affected by Snatch or Magic Bounce, the following Z-move is affected in the same manner its base move is. (UltiMario)
 - Z-Moves are affected by abilities that affect damage or redirect such as Storm Drain and LightningRod. (yetanotherperson)
 - Z-Nature Power transforms into the respective Z-move based on terrain (i.e Energy Ball -> Bloom Doom, Earth Power -> Tectonic Edge) (OmegaDonut)
 - Z-Parting Shot and Z-Memento also restore HP of the incoming Pokemon (need to test the amount). (OmegaDonut)

All of these are fixed, i ran the tests on the latest version of PS on a test server, so i don't have replays. I didn't have time to test the rest atm

**Comment by MacChaeger** [comment]
- POKEMON returned its decreased stats to normal using its Z-Power!. Stat resetting Z-effects remove lowered stats not boosted stat changes, similar to White Herb.
- Z-Geomancy still requires a charge turn after applying its Z-effect. (ih8ih8sn0w)
- All stat increase status Z-move effects do not increase accuracy and evasion. (UltiMario)
These work properly: http://replay.pokemonshowdown.com/gen7customgame-539415390

- Z-Status moves do not have perfect accuracy like damaging Z-moves. (OmegaDonut)
- Purify Z-Move all-stats up effect is applied to the user not the target. Purify does not need to succeed to give those stat boosts, in-game message: ""X increased its stats using its Z-Power! X unleashes its full force Z-Move! X used Purify! But it failed!" (UltiMario)
These work properly: http://replay.pokemonshowdown.com/gen7customgame-539418511

- Z-Me First works similarly to Z-Mirror Move, the Z-Move variant of the target's move will be used regardless of the Pokemon's Z-Crystal with the Z-Power effect of Me First (Boosts Speed by 2 stages) being applied first. Z-Copycat works in a similar fashion, applying its unique Z-Power effect before using the Z-move variant. (yetanotherperson)
- After applying its Z-effect, Z-Sleep Talk calls upon a random move in the user's move set and uses its corresponding Z-move (ex: Water-type move becomes Hydro Vortex) regardless of their Z-crystal or the move's type. (ih8ih8sn0w) Z-status moves do not gain their Z-Power bonus effect and the move is executed as normal (Blitzamirin)
These work properly: http://replay.pokemonshowdown.com/gen7customgame-539423716
http://replay.pokemonshowdown.com/gen7customgame-539425379
http://replay.pokemonshowdown.com/gen7customgame-539427847
Note: In the second of these two replays, there might be a bug; Z-Copycat should probably be copying Heal Block, not Z-Heal Block.

- When hacked into normal move slots, damaging Z-moves (Hydro Vortex, Bloom Doom, etc) becomes 1 BP / -- Accuracy moves of their respective types. Special Z-moves (Catastropika, pulverizing Pancake, etc) function normally with their actual Base Powers and effects. All normal move slot Z-Moves have 1 PP ( PP Ups don't work). You can use as many normal move slot Z-Moves as you want in a battle. You cannot power up a normal slot Z-Move with a Z-Crystal (it won't recognize the move as that typing at all). (UltiMario) Their PP can be restored with a Leppa Berry. (UltiMario)
-  Pokemon that have transformed due to Imposter or Transform can use a Z-move using that transformed Pokemon's move set as long as they hold the corresponding Z-Crystal. (ih8ih8sn0w)
These mostly work properly: http://replay.pokemonshowdown.com/gen7customgame-539429922
http://replay.pokemonshowdown.com/gen7customgame-539434348
However, while using a Z-Crystal such as Normalium-Z with a special Z-Move like Extreme Evoboost is supposed to work (although I don't think it should be called Z-Extreme Evoboost like it is on PS), the same crystal should _not_ work on Breakneck Blitz. The first replay shows that instead of simply not being able to select the move for use with the Z-Crystal at all (which is what should happen), the Z-Move fails on use, even when called through Z-Sleep Talk.

That's all of the remaining issues on that list, I think, although unique Z-Moves such as Extreme Evoboost used directly from moveslots (called CFZs in the BH community) shouldn't actually have any animation at all unless used with a Z-Crystal of the corresponding type. I wish I still had the video ih8ih8sn0w showed me of this phenomena, but he can confirm this.

**Comment by Zarel** [comment]
Cool, with fc16f4fe4f, this entire list is done. Good work, everyone!
