### ISSUE TITLE
Triple Kick in GSC doesn't do multiple accuracy checks but does in PS

### ISSUE THREAD

**Issue by FredrIQ** [Zarel/Pokemon-Showdown#3239]
It rather just hits between 1-3 times at random, with an even distribution (assuming a fair RNG).

I don't know what generation this was changed, so it might also impact ADV or possibly later.

In pret's source, see effect_commands.asm @ BattleCommand_EndLoop. Relevant code pasted below with comments by me to clarify what it does:

    BattleCommand_EndLoop:
            ...
            cp EFFECT_TRIPLE_KICK
            jr nz, .not_triple_kick
    .reject_triple_kick_sample
            ; Get a random number between 0-2
            call BattleRandom
            and $3
            jr z, .reject_triple_kick_sample
            dec a

            ; If the result is between 1-2, do 2-3 hits (double_hit gives hit count as a+1)
            jr nz, .double_hit

            ; otherwise, just do 1 hit, meaning we're done here
            ld a, 1
            ld [bc], a
            jr .done_loop
            ...
    .double_hit
            ld [de], a
            inc a
            ld [bc], a
            jr .loop_back_to_critical
            ...

And yes, this isn't *on top* of the accuracy checks, it simply doesn't do more than one accuracy check. In all multi hit attacks, including triple kick, "checkhit" (accuracy checking) is done before "critical", so jumping back to critical skips checkhit after the 1st hit.

**Comment by Zarel** [comment]
@Marty-D

**Comment by cadaeic** [comment]
The multiple accuracy checks were introduced in #2495. Prior to that, Triple Kick behaved like other multi-hit moves across all gens. One could fix this problem in Gen II simply by removing the `multiaccuracy` property from the move in the mod.

I did some quick testing in Emerald; using Triple Kick against a Pokemon with +6 Evasion 26 times resulted in 16 misses, 6 single hits and 4 double hits. This is not conclusive but does reinforce my impression that it had multiple accuracy checks since Gen III. I can't find any source on this (Bulbapedia being wrong as usual) so I guess we'll have to rely on @Marty-D.

**Comment by Zarel** [comment]
...@Marty-D

**Comment by Marty-D** [comment]
This is indeed exclusive to Gen 2; added to Known Mechanics Bugs.
