### ISSUE TITLE
TypeScript!

### ISSUE THREAD

**Issue by Zarel** [Zarel/Pokemon-Showdown#3278]
Been meaning to have an issue about TypeScript. I personally really want some sort of type checking in the repo, also because IntelliSense makes coding a lot nicer on VS Code, but also because PS has had at least a few crashes that could have been caught by stricter type checking.

Supposedly, research says that even in the absence of good test coverage and/or TDD, strict typing rarely leads to fewer bugs. I don't normally like going against research, but either way it still has plenty of benefits.

This issue is mostly to see what other contributors think of TypeScript.

**Comment by danpantry** [comment]
I tried this with pokemon showdown. Here's are my frustrations when trying to convert `battle-engine.js`:

https://twitter.com/ARedHerring_/status/833344587183828992
https://twitter.com/ARedHerring_/status/833330440811446273

TypeScript is great, but it'll be hard to get working just due to how incorrect some assumptions are about types in that particular file.

**Comment by Zarel** [comment]
I can't find where I read that static typing doesn't catch bugs, but I've definitely had an Amazon engineer claim it, as well as an article I read online. Both of which seemed to be intended to push me towards TDD.

**Comment by danpantry** [comment]
Static typing won't catch business logic bugs, but it will catch bugs to do with not checking if something is `null`/`undefined`, highlight confusing business logic and so forth :smile:

**Comment by danpantry** [comment]
based on the herpderp in #3272, I'll see if I can't get *something* done with TypeScript over the weekend.

**Comment by danpantry** [comment]
@Zarel is there a chat room that I can communicate with you / other contributors about questions I have? I noticed that there's a Code/Tech room on PS, but I didn't know if that's the right one.

**Comment by AustinXII** [comment]
@danpantry try play.pokemonshowdown.com/dev

**Comment by Zarel** [comment]
Yeah, the Dev chatroom is listed in several places, including CONTRIBUTING.md which of course you read, right? ;) ;) ;)

**Comment by taylor1791** [comment]
One of my co-workers researched to see if unit testing obviates static typing. This was their Master's Thesis. The conclusion was that static typing would have caught bugs that made it into popular opens source python libraries. The thesis did use Haskell, which has a fundamentally different type system than TypeScript. The thesis can be read [here](https://drive.google.com/file/d/0B5C1aVVb3qRONVhiNDBiNUw0am8/view).

This does go against many opinions on the internet and this should not be sufficient to make any decision, but I wanted to provide counter research.

**Comment by Zarel** [comment]
I feel like the biggest argument for TypeScript is that every time we have new OMs, they crash PS due to type errors that could very easily have been fixed... :|

**Comment by Morfent** [comment]
Poring over the handbook, I'm pretty impressed by what it offers. Anything stricter than JS' type system is godsend, let alone the sugar for features JS lacks from other languages, though I don't think TDD should be neglected since the extra insurance of more easily knowing your types are doesn't protect you from screwing up your types. I'm probably not saying anything new, but regardless this is something that looks interesting

**Comment by Zarel** [comment]
@danpantry, anyway, my recent refactor to decisions should at least fix _this_ problem:

https://twitter.com/ARedHerring_/status/833344587183828992

**Comment by Zarel** [comment]
Well, TypeScript 2.3 is a game-changer:

https://github.com/Microsoft/TypeScript/wiki/Type-Checking-JavaScript-Files

It's probably overall better for our use-case, too.

**Comment by juanpaucar** [comment]
@Zarel if you are planning to use ES2017 as output for TypeScript compilation we should make sure that the node version is the appropriate to support such features. I'm making a PR for this. Please check (http://node.green/)

My background has been mostly in Haskell, Ruby and TypeScript so in my short experience i'd say that: You can add tests to cover some cases, but you'll never get to cover all of the branches of possible scenarios (not even with mutation tests). But, if you have a good type system which can represent accurately your domain model then it should not allow an invalid representation of that model and therefore all cases would be already covered by your type system. Though, you can still add tests but mostly integration tests

That said, I'd love to help with moving the application to TypeScript. Is there already a plan? Could I propose one?

**Comment by Zarel** [comment]
PS's usual plan is support the latest Node LTS version (and avoid using any features not supported by the latest Node LTS version). Usually. If there's a more modern feature we really want, we'll write a polyfill, or as a really last resort, increase our required Node version beyond LTS (so far, this hasn't happened yet). `async`/`await` are nice, but we don't use Promises often enough to drop LTS support.

So, in that context, it's probably a bad idea to set TypeScript to `ES2017`. I'll change it to `ES2016` since I believe that's the latest version currently supported by Node 6 LTS.

...actually, currently we use a polyfill for `Object.values` in a few places, so `ES2017` might be necessary to make sure TypeScript doesn't complain about those uses.

**Comment by Zarel** [comment]
As for moving the application to TypeScript: Currently, the plan is to instead move it to TypeScript-jsdoc-compatible JavaScript. This will be easier on third-party server mod writers, and skip the need for a compile step.

**Comment by Zarel** [comment]
Thanks for the link to node.green by the way, it's looks really useful!

**Comment by danpantry** [comment]
> ...actually, currently we use a polyfill for Object.values in a few places, so ES2017 might be necessary to make sure TypeScript doesn't complain about those uses.

You can include libraries by doing the following for any polyfills:

````
{
  "compilerOptions": {
    "lib": [
      "es2017.asyncIterable" // as an example
    ]
  }
}
````

In general, polyfilling with TypeScript is a little messy, but it works

**Comment by Zarel** [comment]
Oh, thanks! That's really useful.

**Comment by Morfent** [comment]
We need to add style guidelines for how we write with Typescript. e.g.

```javascript
class Foo {
    bar: string
    baz: number
    constructor(bar: string, baz: number) {
         this.bar = bar;
         this.baz = baz;
    }
}
```

vs.

```javascript
class Foo {
     /**
      * @param {bar=} string
      * @param {baz=} number
      */
     constructor(bar, baz) {
         this.bar = bar;
         this.baz = baz;
     }
}
```

as well as

```javascript
const fs = require('fs');
````

vs

```javascript
import fs = require('fs');
```

vs

```javascipt
import 'fs';
```

**Comment by Zarel** [comment]
The current plan is to use `checkJs`, which limits us to JavaScript.

The main style issue is that we probably want to use `@param {string} [bar]` rather than `@param {string=} bar` for optional arguments.

**Comment by Morfent** [comment]
How should arrow function parametres be typed when needed? I'm assuming we can't do it with `(foo: type) => {}` type syntax

**Comment by Zarel** [comment]
TypeScript syntax works inside `@param {...}` tags.

**Comment by Morfent** [comment]
It does, with the exception of callbacks like `foo.on('bar', msg => { /* ... */ });` from what I find. The only workaround I've managed to find is defining the callback outside the function it's being passed to and using `@param` then, otherwise TypeScript ignores that or `@ts-ignore`. This isn't a very big issue though, since JSDoc works fine for typing in every other case.

**Comment by danpantry** [comment]
You could just use function statements in this example. It's a few more lines, but the stack trace would be nicer in the event of a failure anyway as you will retain the method name.

````javascript

foo.on('bar', onBar)
......
return foo

function onBar() {
 ...
}
````

**Comment by Morfent** [comment]
I think we need to add some rules to the style guide pertaining to Typescript, such as:
- types that can also be null: `?type` or `type?`?
- spacing for object types: `{[k:string]:any}`, `{[k: string]: any}` or `{ [k: string]: any }`?
- arrays: `any[]`, `[any]`, or `Array<any>`?
- multidimensional arrays: `any[][]`, `[any][]`, `[[any]]`, or `Array<Array<any>>`?
- functions: when would including the parametre and return values like in `(any) => any` be preferable to simply using `Function`, or vice versa?

As well as which JSDoc comments are acceptable;
- `@document` is not
- `@param`, `@type`, `@typedef`, `@return` are
- what about `@class`, `@extends`, `@constructor`, `@property`, `@name`?

**Comment by Zarel** [comment]
`?type`

`{[k: string]: any}`

`any[]`

`any[][]`

`(any) => any`

Ask when they come up.

**Comment by Morfent** [comment]
For style with nullable/possibly undefined types, I think it'd be better to write them as `type?`/`type=` instead of `?type`. Typescript's picky about how those are written, and `=type` is not valid syntax for function parametres

**Comment by Zarel** [comment]
I guess...

**Comment by Zarel** [comment]
TypeScript is currently partially implemented.

I'm still thinking about actually transitioning to `.ts` files. It would fix approximately half of our struggles with TypeScript. And I can make the launcher automatically compile them (incrementally, even! thanks to the incremental compiler I just implemented for the client). Our error messages would preserve the line number, and I could probably even silently rewrite the error messages to correspond to the original `.ts` file lines.

Thoughts?

**Comment by HoeenCoder** [comment]
One of the questions I have is how different is a `.ts` file from a `.js` file? Is it just JS with some add-ons and a build step? If its not really different I would be more comfortable with a swap, regardless I should look into this more when I get some time in a few days.

**Comment by Zarel** [comment]
It's a build step and makes writing TypeScript a lot easier, in particular, a not-null assertion is `!`, and casts and type definitions are also a lot more concise.

A few of the ugliest hacks in `dev-tools/global.d.ts` and `dev-tools/globals.ts` would no longer be necessary. A few other ugly hacks we use will probably also stop being necessary.

**Comment by Zarel** [comment]
On the _other_ hand, we'll have to use `type | null` instead of `type?`, but that's a small price to pay.

**Comment by scheibo** [comment]
> Our error messages would preserve the line number, and I could probably even silently rewrite the error messages to correspond to the original `.ts` file lines.

This is pretty trivial with '[source mapping](https://www.npmjs.com/package/source-map-support)'. Simply adding `require('source-map-support').install();`. to the `./pokemon-showdown` script or test runners etc should be enough. Its also supported by Chrome etc so you can debug the `.ts` code directly.

> There's no work started on TypeScript migration yet, but the plan is pretty straightforward: just rename the files to `.ts` one at a time, and add a compiler to `./pokemon-showdown`.

_Originally posted by @Zarel in https://github.com/Zarel/Pokemon-Showdown/pull/5181#issuecomment-465403979_

I'm happy to get the ball rolling on this, however, I'm running into problems  that maybe you have the answer to?. I've converted projects to Typescript before (eg. I [extracted and rewrote the damage calc in Typescript](https://github.com/pkmn-cc/dmg) and hope to eventually upstream it after some polish), but I did that as one big chunk instead of piecemeal.

Say I take one file (`sim/prng.js`, because its short) and rewrite it in Typescript (a723e0a). I then run into problems because I want to make `tsc` emit code (currently our `tsconfig.json` has it set not to), but by default it will do it in the same place. However, this causes errors regarding the JS files:

```
error TS5055: Cannot write file 'Pokemon-Showdown/config/config.js' because it would overwrite input file.

...

error TS5055: Cannot write file 'Pokemon-Showdown/sim/side.js' because it would overwrite input file.

error TS5055: Cannot write file 'Pokemon-Showdown/sim/team-validator.js' because it would overwrite input file.


Found 147 errors.
```

You can configure `tsc` to ouput to an `"outDir"`, say `"./build/"`. However, it only does this to the files which we `"include"`. Because only part of the project is typed, we now have half the JS in one tree and half in another. One solution would be to have a secondary step for the build to copy the compiled JS files out build and into the main source tree - I think this is what the client does (to get `src/*.ts` into `lib/*.js`)? This is kind of ugly IMO, with the build artifacts intermingling with source, but I guess the client sets precedent (I don't think its a problem with like object files in other languages, because one format is binary and one is text, that's not the case with 'compiled' Typescript). We could alternatively copy the source files into `build` and run `./pokemon-showdown` against the `build` directory.

Apologies if I'm missing something obvious.

> I'm still thinking about actually transitioning to `.ts` files. It would fix approximately half of our struggles with TypeScript. And I can make the launcher automatically compile them (incrementally, even! thanks to the incremental compiler I just implemented for the client). 

Can you point me to this incremental compiler? Is it in [`build-tools`](https://github.com/Zarel/Pokemon-Showdown-Client/tree/master/build-tools) and I'm just missing it?

**Comment by Zarel** [comment]
Hm, what's the fastest compiler that supports TypeScript and either source maps or preserving lines?

https://github.com/swc-project/swc is a recent one I saw, I don't see support for either feature, though.

I would probably have `tsc` emit code to the same directory, at least until an entire directory is converted. After the entire directory's converted, then we can split up source and build directories.

**Comment by Zarel** [comment]
I also have questions about how much performance overhead `source-map-support` has. We use stack traces in prod, after all.

**Comment by scheibo** [comment]
> Hm, what's the fastest compiler that supports TypeScript and either source maps or preserving lines?
> https://github.com/swc-project/swc is a recent one I saw, I don't see support for either feature, though.

By 'fastest' do you mean compile times, or the performance of the generated code? And do we care about the former - sure `tsc` is slow, but is `./pokemon-showdown` startup time that concerning? (Or is this about tests? The `npm run test` script already includes `tsc`? Is this so `npx mocha` is fast? We could configure incremental compiles?)

> I would probably have the compiler emit code to the same directory, at least until an entire directory is converted. After the entire directory's converted, then we can split up source and build directories.

That's the problem - this doesn't seem to be an option for the project. Unless there's some magic configuration values I'm not aware of (I'll go comb through the `tsconfig.json` docs), we'll just get a bunch of `TS5055` errors like I pasted above. I'm assuming you know something I don't, because you already did this on the client?

> I also have questions about how much performance overhead `source-map-support` has. We use stack traces in prod, after all.

I could be mistaken, but I believe source maps work after the fact. ie/ you get a stack trace from prod and combine it with your source map locally to determine where the actual location is. Thus zero performance overhead outside of perhaps minor differences at compile time. I'll dig around and try to find links for it, but thats how it works internally at my company with other tools (I haven't used Typescript at work, but have used/worked on other transpilers).

**Comment by scheibo** [comment]
> I'll go comb through the `tsconfig.json` docs.

Nothing jumps out at me from http://json.schemastore.org/tsconfig and https://www.typescriptlang.org/docs/handbook/compiler-options.html. Maybe we could use `--outFile` to put everything into a single file?

> I'll dig around and try to find links for it.

https://www.html5rocks.com/en/tutorials/developertools/sourcemaps/ seems to be a pretty good explanation. I think the `node-sourcemap-support` package I linked probably would add overhead as it rewrites the stacktraces, but as the article outlines there are different alternatives which wouldnt impose that overhead at runtime.

**Comment by Zarel** [comment]
> By 'fastest' do you mean compile times, or the performance of the generated code?

I mean compile times. Generated code should be roughly equivalent at this point.

> And do we care about the former - sure `tsc` is slow, but is `./pokemon-showdown` startup time that concerning?

Yes; fast feedback loops are important for quick development. Especially since there's no real tradeoff. I'm no fan of using tsc for compilation; it's not particularly featureful as a compiler, as you seem to be discovering.

> That's the problem - this doesn't seem to be an option for the project. Unless there's some magic configuration values I'm not aware of (I'll go comb through the `tsconfig.json` docs), we'll just get a bunch of `TS5055` errors like I pasted above.

Sounds like a good reason to use a different compiler. :p

> Can you point me to this incremental compiler? Is it in [`build-tools`](https://github.com/Zarel/Pokemon-Showdown-Client/tree/master/build-tools) and I'm just missing it?

https://github.com/babel/babel/pull/8877

In the client, it's just shoved into the repo:

https://github.com/Zarel/Pokemon-Showdown-Client/tree/master/build-tools/babel-cli

Anyway, the server doesn't need to compile down to ES3, so there's no need to screw around with Babel like this. I'd rather just use an off-the-shelf compiler designed for speed, like `swc`.

> I'm assuming you know something I don't, because you already did this on the client?

The client puts TypeScript in `src/` and JavaScript in `js/`, and sets the TypeScript outdir to `js/`. In hindsight, a similar trick might work here, too.

**Comment by Zarel** [comment]
> The client puts TypeScript in `src/` and JavaScript in `js/`, and sets the TypeScript outdir to `js/`. In hindsight, a similar trick might work here, too.

Oh, perhaps more importantly, the client uses globals for everything, there's no `require`/`import` paths to worry about.

**Comment by scheibo** [comment]
Yep. The paths all become bundled.

I'm also having trouble with hybrid the hybrid js/ts requires. I can do something like 043d4f8 for importing types, but I haven't figured out yet how to require `sim/prng.ts` in `sim/battle.js` for instance (where we need to actual constructor, not just the type).

My take from Googling is that theres not really a blessed path forward for an already jsdoc typed project to convert piecemeal (let alone a partially typed project like PS). It seems you can either type in jsdoc for js files or type in ts files, but mixing the two is not really that clearly supported.

**Comment by Zarel** [comment]
You might need to convert the entire `sim/` directory at once. At least it's comparatively small.

**Comment by Zarel** [comment]
You can also remove `--strict`, so it's easier, and then slowly bring it back one file at a time.

**Comment by scheibo** [comment]
> You might need to convert the entire `sim/` directory at once. At least it's comparatively small.

This would only work if none of the other typed-JS code depends on things within `sim/` (which they don't because they definitely want `sim/dex.js`). And even then I'm not sure it would work because I don't know about how clever Typescript is with ordering (will it know to compile and emit code from `sim-ts/` to `sim/` so that all the other JS `require`s work? I highly doubt it). I also think we'd need to convert `sim/`s dependencies (`data/`, `lib/streams.js`) for it to compile.

Even if this approach did work, it would still be forcing us to effectively be converting directories at a time, and while `sim/` is relatively small, its not an ideal approach.

> You can also remove `--strict`, so it's easier, and then slowly bring it back one file at a time.

Yeah, I kind of wanted to avoid that. It seems really garbage to have to basically lose the benefits of type checking during the period of migration between typed-`.js` and `.ts`. :(

What do you think of using `--outFile` to merge all of the source files (`.js` and `.ts` into a single file)? It might also be a non-option because of the "`.js` doesn't seem to be able to `require` from `.ts`" issue I'm encountering, but if i can resolve that issue then `--outFile` might let us allow us to do files one by one

**Comment by scheibo** [comment]
Ugh. TBH, at this point after wrestling with trying to get typed-JS and ts to play together I'm debating whether it might just be better to bite the bullet and create a feature branch where all 150 files are migrated to `.ts` in one go. "it shouldn't be too hard" given everything is already typed, the main concern would be doing the migration during a period of time where `master` isn't being updated too frequently and conflicts could be kept to a minimum.

**Comment by Zarel** [comment]
> This would only work if none of the other typed-JS code depends on things within `sim/` (which they don't because they definitely want `sim/dex.js`). And even then I'm not sure it would work because I don't know about how clever Typescript is with ordering (will it know to compile and emit code from `sim-ts/` to `sim/` so that all the other JS `require`s work? I highly doubt it). I also think we'd need to convert `sim/`s dependencies (`data/`, `lib/streams.js`) for it to compile.

It's unclear to me why this would be the case. Most of our dependencies are currently globals, anyway (for hotpatch compatibility), so we have _some_ of the affordances that allow us to intermix things in client.

**Comment by scheibo** [comment]
I'm trying to convert `sim/`. I don't think it will work, but YOLO.

Very interesting the types of things Typescript catches with `.ts` filles that `checkJs` seems to miss:

<img width="814" alt="screen shot 2019-02-23 at 19 48 33" src="https://user-images.githubusercontent.com/117249/53294870-2ff10680-37a4-11e9-912b-f6a1a138f112.png">

Unless I'm mistaken and `{Pokemon} [pokemon]` in the JSDoc should not be translated as `pokemon?: Pokemon` in Typescript, it seems like the compiler is also better at actually noticing things that could be `undefined` (which, if we know they can't be in this particular circumstance we can trivially fix with `action.pokemon!.position` etc). My point being, it seems like we get better type checking in `.ts`

**Comment by scheibo** [comment]
Did a [rough conversion](https://github.com/pkmn-cc/Pokemon-Showdown/tree/tsc) for all of `sim/` except for `battle.js` - I'll tackle it in the morning and start actually trying to compile things to prove why I'll actually probably need to convert all typed-JS in one go (I'd of course love to be wrong).

`dex-data.js` is the worst with all the fields, and Typescript really hates the `Object.assign` pattern being used - had to use tons of `// @ts-ignore` for `error TS2565: Property 'Foo' is used before being assigned.`. I have an idea for a Typescript-friendlier pattern, but just converting over the existing code as-is is my main goal - I plan to `// @ts-ignore` most new potential bugs identified by `tsc` with the `.ts` files and then go back later and try to eliminate as many as possible.

**Comment by Zarel** [comment]
You may be interested in my TypeScript-friendlier pattern:

https://github.com/Zarel/Pokemon-Showdown-Client/blob/master/src/battle-dex-data.ts

Although unlike server, client explicitly discards unrecognized data.

**Comment by scheibo** [comment]
Yup, thats basically it. Just do the `Object.assign`s to merge the `data` and `moreData` etc and come up with an `any` object, then pull fields off of it. Pretty easy, but I'm trying not to make any logic changes whatsoever, just rote conversion to limit the scope.

**Comment by scheibo** [comment]
> I then run into problems because I want to make `tsc` emit code (currently our `tsconfig.json` has it set not to), but by default it will do it in the same place. However, this causes errors regarding the JS files
_Originally posted by @scheibo in https://github.com/Zarel/Pokemon-Showdown/issues/3278#issuecomment-466565545_

Thought of a workaround for this - we'll have two separate configs:
 - the current one which is `strict`, `checkJs`/`allowJs` and is used for type checking, not compiling/emitting
 - a new configuration, which includes just the `.ts` and doesn't support `.js`, but emits

The emitting configuration will be used by swc/sucrase/tsc or whatever #5199 lands on for `./pokemon-showdown`/`build` runner in `package.json`.

> It's unclear to me why this would be the case. Most of our dependencies are currently globals, anyway (for hotpatch compatibility), so we have _some_ of the affordances that allow us to intermix things in client.
_Originally posted by @Zarel in https://github.com/Zarel/Pokemon-Showdown/issues/3278#issuecomment-466705089_

Yes and no. I dismissed this original, but  you're correct that globals will buy use some affordances provided that they are defined (and not just declared) in `globals.ts` (**not** `server/index.js`, which can't `require` the `.ts` files to `new` up the global instances`).

---

Here we go: https://github.com/pkmn-cc/Pokemon-Showdown/tree/tsc/sim - fully converted. The problem is `sim/` is not perfectly encapsulated - some `random-team.js` files rely on being able to `require` and call `new PRNG`, and `data/mods/ssb/moves.js` uses `new Pokemon` thanks to something called `'wondertrade'`.

I'm going to dive into `data/` now...

**Comment by scheibo** [comment]
Alright: converting all the `data/**/random-team.js` and `data/mods/ssb/moves.js` seemed to do it, as `npx tsc` now compiles without errors. `npx mocha` on the emitted code fails catatrophically - I think maybe because I tried to change the import pattern from `export = ...` to `export class ...` to be more idiomatic in a lot of places. Who knows. Will try again tonight.

**Comment by Zarel** [comment]
I'd rather spam `@ts-ignore` in the random team and mods than convert them, tbh.

**Comment by scheibo** [comment]
Alright, noted. We can evaluate that approach once I get things working. Right now I'm just doing whatever I can to get a working prototype.

**Comment by scheibo** [comment]
**BOOM!** We're in business! I've got `npm run test` working with all tests passing on my branch!‍ :D 

Here's what's left:

- [ ] keep synced to `HEAD` until it can be reviewed and land (*\*gulp\**)
- [ ] revert `data/**/random-teams.ts` and `data/mods/ssb/moves.ts` conversions and try to use`// @ts-ignore` to get around the problems instead as per https://github.com/Zarel/Pokemon-Showdown/issues/3278#issuecomment-4668248284828
- [ ] set up `build` script which runs `npx tsc -p emit.json 2>/dev/null` and use it in `./pokemon-showdown`
- [ ] see if its possible to resolve the complaints in the above step that have me piping to `/dev/null`, purely because it would be cleaner
- [ ] try to set up `swc` or `sucrase` as the compile step instead of `swc`. This is tracked in #5199. @Zarel: is using `tsc` as the compiler for the time being a blocker that would prevent you from merging my PR? 

Follow up after landing:

- [ ] remove as many `// @ts-ignore`s as possible and clean up types

**Comment by scheibo** [comment]
From https://github.com/Zarel/Pokemon-Showdown/issues/5199#issuecomment-466859039 I actually think using sucrase renders two of those bullets obsolete because it doesn't give any warnings/errors and is mad fast and probably even simpler to use than `tsc` plus a special `emit.json` config. (Y)

**Comment by scheibo** [comment]
My [branch](https://github.com/pkmn-cc/Pokemon-Showdown/tree/tsc) is currently synced to `HEAD` (there were only 3 small merge conflicts, all related to 3 of my previous commits, doh). I might find time before/after work tomorrow to make `./pokemon-showdown` auto build it and then do a pass to polish the changes  as I kind of blitzed through this and it definitely needs a sanity check. Still, happy with how it turned out! It was simultaneously a bigger and smaller job that I thought it would be.

**Comment by Zarel** [comment]
I notice you're using `type` where the standard is to use `interface`. e.g. `type ChosenAction = {` should probably be `interface ChosenAction {`.

**Comment by Zarel** [comment]
Sucrase seems fine to me. The only part that would be an issue is initializing properties where they're declared, but I guess we can just avoid doing that.

**Comment by scheibo** [comment]
Given `sim` and `lib` are now native Typescript, and work on `server` is underway, I don't know that this issue still needs to be open. We are not fully on Typescript yet, but its hard to see us going back now.
