### ISSUE TITLE
Nodejs high CPU

### ISSUE THREAD

**Issue by svivian** [Zarel/Pokemon-Showdown#3461]
Hi, owner of `pokemondatabase.psim.us` here. I got an alert this morning from my host regarding high CPU on my server. When I logged in, `nodejs` was using >90% CPU constantly. I killed and restarted the server and it seemed to stop but it's just come back again.

![server-cpu](https://cloud.githubusercontent.com/assets/207887/25092904/bf759768-2387-11e7-8275-fa529833d829.png)

(The dip is when I restarted the server.)

There wasn't anyone logged in to Showdown when I went on there, but everything looked to be working fine. So I don't know if the app's got itself into some strange state, or if it's being hit by bots or something.

Are there some logging/diagnostic tools I can use? The basic stdout log shows no errors. The `logs/errors.txt` file was last touched in July last year. I can't see any other useful logs around.

I'm using Node v6.10.2 and latest version of Showdown from Github.

**Comment by Zarel** [comment]
Node.js has a profiler. If this happens again, you'd benefit from using that.

**Comment by svivian** [comment]
Does that work if the app is already running? Otherwise I'd have to leave it profiling for hours/days until it happened again.

I found I can use `netstat` to see current connections to the server, so that will at least tell me if it's some kind of bot attack. So far the problem has not happened again.

**Comment by Zarel** [comment]
You can run Node.js in Debug mode. I don't think it has an appreciable effect on performance. After you do that, you can attach the profiler whenever there's an issue.

**Comment by Zarel** [comment]
I'm going to close because this really isn't the sort of issue that can be tracked down on our end. If it does happen again, feel free to reopen with details.

**Comment by Zarel** [comment]
Looks like this is probably the best way to do this:

https://www.dynatrace.com/blog/how-to-track-down-cpu-issues-in-node-js/

**Comment by svivian** [comment]
Managed to reproduce the problem, so I was able to profile with `nodejs --prof app,js`. The high CPU seems to start as soon as a random battle is started, and continues after the battle was finished.

I've attached all the processed log files, hopefully this can help you investigate. It seems like `node::ContextifyScript::New(v8::FunctionCallbackInfo<v8::Value> const&)` is taking a lot of the time.

[nodejs-isolate-processed.zip](https://github.com/Zarel/Pokemon-Showdown/files/958973/nodejs-isolate-processed.zip)

**Comment by Zarel** [comment]
@Morfent

**Comment by Morfent** [comment]
Sorry for the late reply. I can't say for sure what's causing this, but looking over the logs you posted it looks like an issue with how the simulator and the process manager interact. `node::ContextifyScript::New(v8::FunctionCallbackInfo<v8::Value> const&)` is related to when Node first loads modules, which would explain why it'd appear when you first start a random battle.

The other parts of PS that use the process manager attach ``resolve`` callbacks from promises in the parent process to pass information between the parent and child processes (which really, really isn't a good idea considering it traps the entirety of the promise's context and scope on the heap until called, which is pretty large). Battles don't do that. room-battle.js puts the entire battle object there instead, which I suspect would cause loads of issues related to context and scope.

I'm curious as to why this would happen specifically on Mac and not other OSes, especially others based on BSD like FreeBSD since I use but haven't had this problem. Could you take a few coredumps for me? One after PS has finished loading and you're logged in, one after using something like `/dexsearch` to get dex related functions (de)optimized, and one after starting a random battle. You can use `gcore` to make them, but check the manpage since on my system I need to use the `-s` flag, but not on Linux
