### ISSUE TITLE
Adding "Fairness" to Random Battles

### ISSUE THREAD

**Issue by IronCross** [Zarel/Pokemon-Showdown#3473]
Random battles are the most popular format without a doubt. Pokemons are assigned completely randomly to both players, so both of them have an equal chance of getting good/bad pokemons. However, it often happens that a given player stands no chance against his/her opponent. In order to eliminate such situations, we could assign pokemons randomly, but make sure the overall BST of both teams is comparable, if not identical.

**Comment by Zarel** [comment]
Level balancing is our attempt to make random battles fair. There's no really known good way to make things even fairer. Standardizing BST is a bad way because it doesn't take into account movepool, abilities, typing, etc. That's why we level balance on tier, which is a good way to take into account a number of factors that a simple BST calculation would miss.

**Comment by Zarel** [comment]
On one hand I see the value in an issue about randbats balancing, but this issue contains no actionable suggestions, and I think randbats balancing is currently mostly fine. Anyone who wants to bring up something new can make a new issue; I'm closing this one.
