### ISSUE TITLE
Dex.js error

### ISSUE THREAD

**Issue by PrinceSky-PS** [Zarel/Pokemon-Showdown#3604]
Getting this error: https://ibb.co/e2cdav while trying to up server.

**Comment by Zarel** [comment]
Please read the README.

**Comment by Zarel** [comment]
Following the instructions provided in the README would fix your problem.

Specifically, PS should be launched with `./pokemon-showdown`, not with `node app.js`.

Launching with `./pokemon-showdown` will tell you what your problem is: Your Node.js version is too old. Which you could also have learned from the README, which states that PS requires Node 6 or later.
