### ISSUE TITLE
Images Missing for Cap Pikachu

### ISSUE THREAD

**Issue by DanManB** [Zarel/Pokemon-Showdown#3793]
I don't know if this is the right place for this but on [pokemonshowdown.com](url), images are missing for Cap Pikachu.

![image](https://user-images.githubusercontent.com/2660574/28274202-45232d42-6ade-11e7-80e9-c11823fbe0ba.png)

**Comment by Zarel** [comment]
This isn't a _great_ place for it but this is still an issue worth keeping open, the main issue is that I don't personally have backsprites for them. If you could make them and give them to us, that'd be greatly appreciated.

**Comment by Dragotic-PS** [comment]
Stumbled upon this issue here. There was actually a [submission](http://www.smogon.com/forums/threads/sun-moon-sprite-project-dawn-of-a-new-day.3577711/page-10#post-7045991), on smogon forums, regarding ash-pika's backsprite, by nathan. Although it's available on his photobucket gallery, I reuploaded it on [imgur](http://imgur.com/a/LyWX9). All credits to him.

**Comment by Zarel** [comment]
We don't seem to have a front-sprite, either...

**Comment by Dragotic-PS** [comment]
[Here's](http://i.imgur.com/IihQfpZ.png?1) the whole batch of Ash-Pikachu sprites Nathan worked on, including front/back sprites. All credits to him, again.

**Comment by Zarel** [comment]
Can you split that up into separate 96x96 images?

**Comment by Dragotic-PS** [comment]
Will [these](http://imgur.com/a/cOwaU) do?

**Comment by Zarel** [comment]
I _can_ use those if necessary, but if you could center them (and fix the tail being cut off on this one: http://i.imgur.com/7z1IN72.png ), that'd be even better.

**Comment by Dragotic-PS** [comment]
How about [now](http://imgur.com/a/rGpjM)?

**Comment by Zarel** [comment]
Yes! Thank you!
