### ISSUE TITLE
Suggestion: Automatically switch in last Pokemon when only one is left.

### ISSUE THREAD

**Issue by FelixRilling** [Zarel/Pokemon-Showdown#4068]
As there is no choice to decide on for the player, automatically switching in the last Pokemon would slightly speed up battles.

**Comment by Zarel** [comment]
We don't even automatically attack when you're locked into a single move. This seems unnecessary.

The reasoning is something along the lines of: It's generally better if controls are consistent.

A lot of clicking in games is just busywork that could easily be automated away by computers (in StarCraft that's called "macro"!) We don't partially because some people think it's fun, and mostly because it's easier to play a game in which the rules are consistent "you have to click to switch in" rather than context-sensitive "you have to click only if it's not your last pokemon".

**Comment by Zarel** [comment]
To be fair, PTCGO does automatically do things when there's no choice to make, so that _is_ a valid option when designing a game. But that's a game with waaaay more clicking per turn so the tradeoff is different.
