### ISSUE TITLE
Ban Unown from VGC 2018

### ISSUE THREAD

**Issue by DaWoblefet** [Zarel/Pokemon-Showdown#4299]
Unown is currently unobtainable in any Generation VII game, which prevents it from being legally obtained in Alola. As a result, it should not be allowed in VGC 18, which requires the Pokemon be caught/bred/gifted/otherwise obtained in the Generation VII games.

**Comment by Zarel** [comment]
Well, it's a workaround, at least. I was keeping it open while I thought about a full fix.

**Comment by Zarel** [comment]
@Marty-D I guess we could do something like `isUnreleased: 7`? We'd probably have to rewrite every existing use of `isUnreleased`, but I mean there aren't _that_ many.

**Comment by Marty-D** [comment]
If there were more instances of this problem then I agree that would be worth doing, but not just for Unown. It's not even an issue in all current `requirePlus` formats (Battle Spot Special for example uses the Alola Dex so Unown is banned anyway). Everything else in Undiscovered is usually banned anyway, and if they aren't it's because they were catchable in the latest games.

**Comment by Zarel** [comment]
I think it could make implementing future generations easier, too.

**Comment by Marty-D** [comment]
>I think it could make implementing future generations easier, too.
I'm not seeing it, do you have an example? As far as I can tell this situation should never happen again.

Allowing certain Pokemon in a format which requires Pokemon to be from the current generation and yet not having released the certain Pokemon in said generation isn't something that has ever been done until now. And again, only relevant to Unown since it can't breed.

**Comment by Zarel** [comment]
Specifically, when a new generation is released, sometimes past-gen Pokémon can't be accessed. Twice so far, Game Freak has restricted Pokébank access until sometime into the gen. During this time, various past-gen Pokémon are inaccessible. We have previously done this by setting `isUnreleased` in the current gen and setting `isUnreleased: false` in the next past gen, but this would make it so we would only have to set it in one place, and handle the rest in the validator.

**Comment by Marty-D** [comment]
Oh, I thought we were talking about official formats. Bank availability is a fair point for Smogon formats.
