### ISSUE TITLE
Players Cannot Join Created Tournament

### ISSUE THREAD

**Issue by PatrickL789** [Zarel/Pokemon-Showdown#5154]
I am helping a friend set up a server. When we teat the code on a hosted server, and try to create a tournament, we are encountering a message that says “one of your alts has already entered this tournament” when other people try to join the created tournament even though no participants have entered the tournament yet. As a result, no one can join the tournaments we create.

How can we resolve this issue?

**Comment by HoeenCoder** [comment]
Most likely, you and your friend have the same IP address, this could be due to the server, or it may be because you both are in the same location (if thats the case at all). Users with the same IP are considered alts. Theres a few ways to fix this.

1. Modify https://github.com/Zarel/Pokemon-Showdown/blob/master/server/tournaments/index.js#L1002 and any other calls to this function to have `true` as the second argument to allow alts in tournaments.
2. I think theres a way to fix the same IP issue if its the server's fault, though I don't remember it myself sorry. Someone else might be able to answer this though!
3. If your both simply in the same place, being in different places or one of you using a device with a different IP (phones usually do) will fix that.

**Comment by Zarel** [comment]
We should probably support making it easier to disable alt checking.

**Comment by Zarel** [comment]
I have `Config.fakeladder` set up for this use-case in the ladder, but we might want to rename it and also add more flexibility.

**Comment by PatrickL789** [comment]
We are not in the same location. So, that eliminates that possibility. It might be the seever then.

**Comment by Zarel** [comment]
My best guess is that your server is behind some sort of proxy. You can use `/ip [username]` to find the IP PS is seeing, and the `proxyip` option in `config/config.js` to "see through" the IP.
