### ISSUE TITLE
Double switch messages sent in wrong order

### ISSUE THREAD

**Issue by davidstone** [Zarel/Pokemon-Showdown#5155]
After two Pokemon faint on the same turn (and thus both sides need to replace their Pokemon), I got messages in the following order (with Stealth Rock down on Swellow's side of the field and Toxic Spikes down on Slowking's):

|switch|p2a: Slowking|Slowking, L83, M|100/100
|switch|p1a: Swellow|Swellow, L79, M|224/224
|-damage|p1a: Swellow|168/224|[from] Stealth Rock
|-status|p2a: Slowking|psn

My understanding of the protocol is that Slowking's status should have arrived immediately after its Switch message.

**Comment by Zarel** [comment]
My understanding is that that's wrong. That's only for a beginning-of-turn double-switch, not a "replace fainted Pokémon" double-switch.

**Comment by Zarel** [comment]
I can ask @Marty-D for confirmation, but I'd be surprised if he said anything different; I remember asking him when we were implementing this behavior in the first place.

**Comment by Zarel** [comment]
> My understanding of the protocol is that Slowking's status should have arrived immediately after its Switch message.

Wait, are we talking about different things? The protocol is supposed to send things in the same order they happen on-cart.

**Comment by davidstone** [comment]
OK, then I have misunderstood the format of the protocol. My understanding (which I did not read anywhere, I just assumed from looking at messages) was that messages that begin with '-' are submessages of the most recent message that does not begin with a '-'.

The only other situation I have run into so far (and worked around) is that messages for waking up and thawing out do not follow that pattern.

I guess I'll have to do something much more complicated to get this to work.

**Comment by Zarel** [comment]
Oh, no, they're not.

Approximately, messages that begin with `-` are minor messages.

Approximately, minor messages are rendered in small font, and major messages are rendered in normal font.

More precisely, major messages form a "summary" of a battle: what turn it is, what moves were used, what Pokémon fainted, and what Pokémon permanently changed forme.

But minor messages aren't usually but not always associated with a previous major message. You've probably already realized that `|` forces a break (to separate the previous move from residual effects, among other things), but also:

https://github.com/Zarel/Pokemon-Showdown-Client/blob/48eb1aad7674a3927e426e7d7539f104bd6a79c2/src/battle-text-parser.ts#L264-L315

Natural Cure, Protean, and the Confusion/Attract warning are hardcoded to be associated with the next major message, rather than the previous.

Other than that, end-of-turn double-switches are the only other case you need to worry about.
