### ISSUE TITLE
Serializable simulator state

### ISSUE THREAD

**Issue by yuzeh** [Zarel/Pokemon-Showdown#5270]
Now that simulator code is pretty well separated from server code, the idea of serializing and reloading a game in the middle seems way more achievable.

My vision for what this looks like is adding two more operations to the simulator protocol (in addition to `start`, `player`, `p1`, `p2`):
* `dumpstate` -- the process would write a JSON blob to stdout with the current state of the game
* `loadstate <JSON Blob>` -- the process would overwrite its current state with the JSON blob.

Two main use cases come to mind:
* May be useful for debugging and unit testing
* Allows for efficient forward modeling, making methods like Monte Carlo Tree Search (or some partially observed variant of it) possible

Let me know if you'd accept a PR that implements this.

**Comment by scheibo** [comment]
OMG! I am on a mission to do the exact same thing (for MCTS). I wasn't going to add `dumpstate` or `loadstate` though, because the server's true state is != the client's observed/inferred state. I don't know about debugging, but I think it would be relatively useful for recreating games in tournament settings that got screwed up do the DCing etc.

**Comment by Zarel** [comment]
We already have a solution for recreating games – inputlogs are now tracked, and tournament directors know about the `/importinputlog` and `/exportinputlog` commands.

The only advantage of dumping state over inputlogs is performance, since state can be deterministically recreated from inputlogs.

I don't have a problem with supporting serializing simulator state if you want to implement it, though.

**Comment by scheibo** [comment]
@yuzeh - I'm probably still a month or so away from being ready to implement it, but it seems like the PR would be accepted if you wrote it ahead of that. I'd be happy to review or offer support if you wanted to take it on.

**Comment by yuzeh** [comment]
`loadstate` would be excellent for loading a particular game state without having to read the whole inputlog up until that point. `loadstate` would also be good for loading hypothetical states (i.e. ones not necessarily generated by `savestate`) and potentially invalid states as well.

@scheibo great to hear that you're looking into MTCS for Pokemon battling! I'm using RL (without any forward search) right now and seeing promising results in gen7randombattle. That said, I won't have very much time to implement this in the next two months...

**Comment by scheibo** [comment]
Alright, well then I might get to it first, but Ill loop you in to see that my solution works for you if I do. :)

I'm currently working to try and modularize Showdown further to make it more useful for developers to use as the foundation for things like AIs, as well as speeding it up for applications like MCTS. From benchmarking, when I started the average game was taking about 0.4s ([pkmn.cc/optimize](https://pkmn.cc/optimize) has more details) which seemed like it wouldn't work well for naive MCTS. I'm fairly confident the work I plan to land soon (changing `findEventHandlers` to use lookup instead of searching, minimize `toId` calls, etc) can get us below 0.1s/game on average, but playouts are still going to be slow - Pokemon is a whole lot more complicated than a game like Go or Chess where there are only so many moves and the engine can be implemented with tables/arrays/matrices (note: I of course don't want to imply that those games don't have emergent gameplay complexity that springs from their simple rules). Even parallelizing playouts, it seems like it will be difficult to be fast enough to be truly strong with pure MCTS, so having some game state evaluation function (likely gleaned through ML) seems like the way to go.

**Comment by Zarel** [comment]
Hypothetical states _can_ be induced by `>eval` inputs, but I don't doubt that editing a serialized state might be easier.

**Comment by yuzeh** [comment]
@scheibo This analysis looks excellent.

At the risk of going a bit off topic... I suspect if you decide to do something like AlphaZero, your runtime is going to be dominated by NN inference, so optimizing this portion may not have as much of an overall impact. (For reference, my self-play setup completes matches at a rate of ~10s/match on one CPU core.)

**Comment by scheibo** [comment]
They're two different concerns - I won't be doing NN inference during a real game (where I'm on a clock), only during the training phase (where it matters significantly less). I'd be leveraging the precomputed policy and evaluation functions during gameplay which would be quick (and yes, AlphaZero is an inspiration). Or am I misinterpreting you?

Also, I think I'm going to take on this bug sooner. It's not as simple as just `JSON.stringify(battle)` because of circular references, but I'd just replace those with indices instead (`stringify` takes a transformer function as one of its args, so its pretty straight forward). I was also blocking on figuring out the 'best' state object, with things like typed `volatiles`/`sideConditions`/etc instead of `AnyObject`, but I think its better to just get serialization and restarting working and then bikeshed about the representation.

**Comment by Zarel** [comment]
Incidentally, the spec defines a `toJSON` function which can be overridden, which is the approach I'd recommend.

**Comment by yuzeh** [comment]
@scheibo if your policy and value functions are neural networks, you will need to perform inference on them during play time.

Let's continue this discussion offline! Feel free to email me at the address on my profile :)

**Comment by scheibo** [comment]
@Zarel - overwriting the `toJSON` method would mean I then have to enumerate all the fields (and `Battle` has a lot...) which seems error prone because then someone will add one and forget to update it (because while I'll definitely add tests for serializing, it will be impossible to cover all possible battle states). `JSON.stringify(battle, replacer)`  would be shorter and more robust to future changes?

`toJSON` + `fromJSON` seems like all that is required for this bug, but its not super great for practical use cases IMO because its tied so closely to the implementation details of `Battle` (I mean, it's actually still super useful for a [PocketMon](https://docs.google.com/document/d/1xKy1b1SExXqlb6KXfmfbuifVCjAgPUbnusekIZuKQ8s/edit#heading=h.jb61j01iy1m4) MVP because I'm going to make the AI pseudo-omniscient to begin with anyway). 

What my real end goal is to have a `toState` and `fromState` methods, where the `Battle` 'state' is a more strongly typed representation of the true battle state (for standard metagames only; support for future OMs means that its impossible to lock down an authoritative state for all Pokemon battles). My goal is to be able to build up a similar state object on the client purely by observation and inferrence, and then be able to instantiate a *possible* server state (there are some things which are impossible to observe due to their stochastic nature, the most obvious being `prngSeed`) which can be then passed to `Battle#fromState` to be able to play out the rest of the game from that perceived possible reality.

@yuzeh - I'll maybe reach out when I'm closer to actually implementing it an AlphaZero-like AI. There's a lot of ground to cover before then... :)

**Comment by Zarel** [comment]
@scheibo There's nothing the `replacer` can do that `toJSON` can't. `toJSON` seems far more robust to me - you can have serialization code for `Side` in the `Side` class, for `Pokemon` in the `Pokemon` class, instead of needing to have a weird string-based replacer forced to handle it all in one place?

You can simulate the `replacer` approach with a `for..in` loop in your `toJSON` function – `toJSON` overall seems much more flexible and benefits all serialization.

**Comment by Zarel** [comment]
Like I feel like you're missing something – your `toState` function should definitely exist, but why should it not be named `toJSON`?

**Comment by scheibo** [comment]
>  There's nothing the replacer can do that `toJSON `can't.

Fair enough. There's literally nothing stopping me from iterating through keys in the exact same way `JSON.stringify` does. Brainfart, sorry.

> you can have serialization code for Side in the Side class, for Pokemon in the Pokemon class

(Y)

> Like I feel like you're missing something – your `toState` function should definitely exist, but why should it not be named `toJSON`?

`toJSON` returns a `string`, `toState` could return a `State` which can then be type checked. Basically, `toJSON` + a guaranteed schema for the JSON representation. Though they're obviously related, `toJSON` would be trivial to implement as `JSON.stringify(this.toState)`.

**Comment by Zarel** [comment]
@scheibo I think you're misinterpreting what `toJSON` does. `toJSON` does not (necessarily) return a string; it serializes an object into JSON-representable data:

![image](https://user-images.githubusercontent.com/551184/54049858-5c911f00-41a3-11e9-9ad7-1d0d96154c90.png)

**Comment by Zarel** [comment]
In other words: `toJSON` can and should return a type-checkable `State` object.

**Comment by scheibo** [comment]
Oh! I didn't know that. I guess I should have looked at the docs. Then yes, `toJSON` is precisely what I want :)

**Comment by scheibo** [comment]
Starting work on this now :)

**Comment by scheibo** [comment]
1d43e8f8c10900215dcf7d7904d1319a20eed464 is my naive foundation - iterate through keys, have one representation of `Pokemon` | `Side` | `Field` | `Battle` and turn the rest into references that can be decoded with `Battle.fromJSON`, cutting out fields which can be derived/are immutable data etc. Lots of things missing, just wanted to throw something up to begin iterating on/polishing. (also, I'll define `PokemonState`, `SideState` etc or whatever name we want objects to be returned from the `toJSON` methods to provide stronger indications about type we're returning than `AnyObject`, though it'll obviously need to rely on a cast and/or `//@ ts-ignore` given the implementation is dynamic).

https://gist.github.com/scheibo/d05dbb7a9665b7e0fc9537d338cb008e is the resulting JSON 10 turns into a random battle, just to see how it looks.

My goal is to have the most compact and simple JSON representation possible which still plays out the game. I am **not** aiming for `assert.deepEqual(Battle.fromJSON(battle.toJSON), battle)`, because I don't think we should be saving all the state in battle, like the caches in Dex. I believe **the deserialized battle should play out exactly the same** though, so I plan to accomplish this by using my harness/smoke tests to play battles normally and serializing + deserializing each turn and ensure the logs/result match at the end.

**Comment by Zarel** [comment]
Looks good so far, although I really do wish all the `effectData` stuff would be renamed to `effectState`, and also we should probably get rid of `effectState.id`.

**Comment by scheibo** [comment]
This is turning out to be just as deceptively challenging as anticipated :) 2098bee08fc85f8720ea410702d806f4242fb57e includes deserialization with a couple TODOs and presumably a bunch of bugs.

- Typescript is giving me grief about the types in `REFERABLE` with errors like `Type 'Ability | undefined' is not assignable to type 'import("sim/dex-data").Ability | undefined'.`, which is rather obnoxious and I can get past it with `any` obviously, but I feel like it should work so I'm probably just 'holding it wrong'. This reminds me of the frustrations I was running into with the Typescript refactor Typed `.js` -> `.ts` interop :(
- `ActiveMove` is a PITA, but at the same time making it not a `class` anymore wouldnt make things more hacky I think (would need to look for 'known fields' instead of the `constructor`), and the old way wasn't very monomorphism friendly. I'll file a bug about it so we can discuss options once I've given it more thought and work through the concerns Zarel had with it originally.
- Really glad I made certain fields `readonly` during my cleanup refactorings, but I have a feeling the fact that things can't be made to be deeply immutable and the fact we are somewhat fast and loose with `// @ts-ignore` and `/** @type {...} */ or `as` in places will cause me to pull my hair out :)
- I'm trying to support as much as possible, but if obscure other metagames can't be round trip through serialization I'm OK with that.
- I'm also not sure serialization at any arbitrary point in the battle will work. My goal is to make it so that at each 'action/decision point' (ie/ when `Battle` is waiting on a request, which is usually each turn but could be mid turn for faints or U-turn/BP/etc) can round trip. Like with OM support, I'm not going to rule out trying to make serialization work for every point in the lifetime of the `Battle`, but I'm also going to focus on the core use case first.
- Not to toot my own horn, \<brag\>but the harness/smoke tooling is indispensible here (and in general TBH). Make changes, run 100 battles, see if anything crashes before bothering to write any tests. Given that I'm lazy, I really like that workflow :). Smoke tests may not catch a ton of crashes  in release verification, but in development its proving to be super interesting!\</brag\>

I've created a new `sim/state.ts` class for this, because lord knows `Battle` doesn't want to continue to be a dumping ground, and having all the serialization + deserialization together in one place makes things a lot more readable IMO (the `toJSON` methods of the actual classes just delegate to these methods).

>  I really do wish all the `effectData` stuff would be renamed to `effectState`, and also we should probably get rid of `effectState.id` and `effectState.target`.

I'm happy to rename `effectData` -> `effectState` as a refactoring (I assume you mean in the actual code, not just make an alias in the JSON representation?). Do you also mean 'effect' in the more general `fooData` sense (`itemData`, `abilityData`, etc), or simply the `effectData` field on `Battle`?

**Comment by scheibo** [comment]
> Typescript is giving me grief about the types

Turns out this is because of my good friend, `globals.ts`. `tsc` doesn't see that the definition in `dex-data.ts` and in globals are the same. If I have the `dex.ts` return `Data.Foo` instead of the bare `Foo` it fixes `state.ts` (but breaks lots of other places, because people are accessing attributes they really shouldn't be). Really, I need to get rid of the duplicate declarations, as it really seems to fuck up the compiler and makes us less type safe.

**Comment by scheibo** [comment]
I've figured out how to appease the compiler, so now I've got things type checking and serializing/deserializing (I should really fix `globals.ts` at some point, but I can at least punt on that a little longer). ec7d32c05c9669e96d182535540c738eb4f5956a

First test is to compare the JSON through a round trip.

```javascript
const toJSON = JSON.stringify(this, null, 2);
console.log(toJSON);
const fromJSON = Battle.fromJSON(toJSON);
console.error(JSON.stringify(fromJSON, null, 2));
```

```
$ node dev-tools/harness.js 1 >~/to.json 2>~/from.json && diff ~/to.json ~/from.json
```

And we're good! w00t! (getting a little bit too excited by this, but this feature was literally the reason I started looking into the PS codebase to begin with, so its fun to feel like I'm finally confident enough to work on it productively)

One gotcha is the use of `delete` in the codebase, which means there are sometimes mismatches where one side is `null` and the other is absent. Seems straightforward to fix.

Once I fix the `delete`s I think I'm ready for stage 2 of testing - trying to play out battles from the round-tripped object. I think I need to create a 'teeing'/'forking' `BattleStream` which can simultaneously send commands to two `Battles` at once, where one of the `Battle` objects is roundtripped between each command.

**Comment by Zarel** [comment]
> Really, I need to get rid of the duplicate declarations, as it really seems to fuck up the compiler and makes us less type safe.

I've been saying this for ages. :p This is like the main thing I wanted to fix after the migration to TypeScript.

**Comment by Zarel** [comment]
We've actually had this problem in the past, too – one of our TypeScript migrations led to error messages like "Type Side isn't compatible with Side".

**Comment by scheibo** [comment]
>  This is like the main thing I wanted to fix after the migration to TypeScript.

I had tried it a couple weeks ago but got frustrated. [I've reprioritized it](https://pkmn.cc/TODO).

**Comment by scheibo** [comment]
This is proving to be challenging.

:)

**Comment by scheibo** [comment]
Testing this is proving to be really challenging due to races - controlling two different streams at once in lockstep and making sure that when we serialize the test and control battles that one of them doesn't have updates not reflected in the other yet is actually obnoxiously hard (I can't lock both reads and writes because we await the `read` while holding the lock, meaning the `write` can never come. Only locking `write` seemed like it should work, but doesn't actually appear to?). Failures also seem to be getting swallowed which makes debugging really frustrating. However, just running battles to the end in the harness and comparing seems to give me identical results (though I'm skeptical because I'm sure it can't be that easy?), but a unit test using `battle.makeChoices` (ie/ `side.autoChoose`) everything gives me divergent results. *\*cries\**

I've pushed the polished up (de)serialization logic to a draft PR with a 'might work, but use at your own risk' caveat and I'm taking a break from this now because its not 'sparking joy'. I will return to it once I've figured out a way to test/forgotten how frustrating it is.

**Comment by yuzeh** [comment]
Thanks for taking this on!

**Comment by szymonWojdat** [comment]
Hey @Zarel, there's no corresponding web API for this, right?

**Comment by Zarel** [comment]
@szymonWojdat what sort of web API would you want?

In general, simulator state is best serialized into input logs, which we have many APIs for, for instance:

https://replay.pokemonshowdown.com/gen8randombattle-1271255556.json

has an `inputlog` field.

The type of serialization in this issue is mostly only for situations that need high performance.

**Comment by szymonWojdat** [comment]
Thanks for the reply. The idea is to be able to save and then recreate a battle from a given turn, it's currently doable in sim but i believe it's not when you're using any web-based client.

**Comment by Zarel** [comment]
What do you mean? We support `/exportinputlog` and `/importinputlog` commands from any web-based or API-based client.

**Comment by szymonWojdat** [comment]
Oh i wasn't aware of these. It seems like `/exportinputlog` doesn't allow for exporting the log before the game is over, I assume it's for security reasons, so that even admins can't look up opponent's team info during the game, right?

**Comment by szymonWojdat** [comment]
I just realized that one workaround for being able to recreate games from a given turn (as this is what I'm looking for) would be to get the output log at the end and then parse and trim it, so I assume I got what I was looking for. Thanks!

**Comment by Zarel** [comment]
> Oh i wasn't aware of these. It seems like `/exportinputlog` doesn't allow for exporting the log before the game is over, I assume it's for security reasons, so that even admins can't look up opponent's team info during the game, right?

It's partially to do with the way we get inputlogs, and partially for security reasons. It's not hard to `/offertie` or `/forcetie` if you need to grab the log at a specific point, anyway.

> I just realized that one workaround for being able to recreate games from a given turn (as this is what I'm looking for) would be to get the output log at the end and then parse and trim it, so I assume I got what I was looking for. Thanks!

Yep! That's a good way to do things.
